input_data:
  # file: "../data/raw/raw_data_file.csv"
  file1: "../data/raw/raw_data_Jobs_NYC_Postings.csv"
  file2: "../data/raw/raw_data_Jobs_NYC_Postings_2.csv"

output_data:
  # file: "../data/clean/cleaned_data_file.csv"
  file1: "../data/clean/cleaned_data_file_NYC_Postings.csv"
  file2: "../data/clean/cleaned_data_file_data_analyst.csv"
  file3: "../data/clean/cleaned_data_file_keywords.csv"
